disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- trailing_whitespace
- file_length

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

excluded:
- Pods
- Carthage

function_body_length:
- 59 # warning
- 60 # error

type_body_length:
- 449 # warning
- 450 # error

line_length:
- 399 # warning
- 400 # error

cyclomatic_complexity:
- 13 # warning
- 14 # error
